using System.Xml;
using System.Xml.Serialization;

namespace DesignPatterns.Repository.StorageՕptions
{
    public class OnXml: Storage
    {
        public static void WriteByReflection<T>(IEnumerable<T> Data, string Path)
        {
            using XmlWriter writer = XmlWriter.Create(Path + @".xml");

            writer.WriteStartDocument();

            writer.WriteComment("This file is generated by the program.");

            Type type = typeof(T);

            writer.WriteStartElement($"{type.Name}s");
            foreach (var item in Data)
            {
                writer.WriteStartElement(type.Name);

                foreach (var Properti in type.GetProperties())
                {
                    var value = Properti.GetValue(item).ToString();
                    writer.WriteElementString(Properti.Name, value);
                }
                writer.WriteEndElement();

            }

            writer.WriteEndElement();
            writer.WriteEndDocument();
            writer.Flush();
        }

        public override IEnumerable<T> Load<T>()
        {
            string filename = nameof(T) + ".xml";
            XmlSerializer xmlSerializer = new(typeof(List<T>));
            using FileStream fs = new(filename, FileMode.OpenOrCreate);
            if (fs.Length == 0)
            {
                return new List<T>();
            }

            return (List<T>)xmlSerializer.Deserialize(fs);
        }

        public override void Write<T>(List<T> source)
        { 
            string filename = nameof(T) + ".xml";
            XmlSerializer xmlSerializer = new(typeof(List<T>));
            using TextWriter writer = new StreamWriter(filename);
            xmlSerializer.Serialize(writer, source);
        }

    }
}
